server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yg0313/config-repo
#          username: private repo
#          password: private repo
#          uri: file://C:\Study_git\DevelopStudy\git-local-repo