server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yg0313/config-repo
#          username: private repo
#          password: private repo
#          uri: file://C:\Study_git\DevelopStudy\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
